version: '2'
services:
  web:
    build: .
    image: challenge
    ports:
    - 8000:8000
    depends_on:
    - db
    - cache
  cache:
    image: "redis:alpine"
    container_name: cache
    ports:
      - "6379:6379"
  db:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    container_name: challenge_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: hcfonseca
      POSTGRES_PASSWORD: hugo123
      POSTGRES_DB: challenge_db